Repository dojo/widgets, pull requests merged in 2019-11, with the labels that each got.

#863 Fix extra rendered calendar header cells in IE
  src/calendar/index.ts
Labels: needs back-port

#865 framework #569: Focus meta invalidation change
  src/calendar/CalendarCell.ts
  src/calendar/DatePicker.ts
  src/checkbox/index.ts
  src/checkbox/tests/unit/Checkbox.ts
  src/combobox/index.ts
  src/combobox/tests/unit/ComboBox.ts
  src/dialog/example/index.ts
  src/dialog/index.ts
  src/dialog/tests/unit/Dialog.ts
  src/listbox/index.ts
  src/listbox/tests/unit/Listbox.ts
  src/meta/Focus.ts
  src/radio/index.ts
  src/radio/tests/unit/Radio.ts
  src/range-slider/index.ts
  src/range-slider/tests/unit/RangeSlider.ts
  src/select/index.ts
  src/select/tests/unit/Select.ts
  src/slider/index.ts
  src/slider/tests/unit/Slider.ts
  src/text-area/index.ts
  src/text-area/tests/unit/TextArea.tsx
  src/text-input/index.ts
  src/text-input/tests/unit/TextInput.tsx
  src/time-picker/index.ts
  src/time-picker/tests/unit/TimePicker.ts
Labels: needs back-port

#878 update interface of title-pane
  package-lock.json
  src/title-pane/index.ts
  src/title-pane/tests/unit/TitlePane.spec.ts
Labels: needs back-port

#906 Add theme prefix and fix classes clash
  src/middleware/tests/theme.spec.tsx
  src/middleware/theme.ts
Labels: bug, enhancement

#925 Popup widget
  package-lock.json
  src/examples/src/config.ts
  src/examples/src/widgets/popup/Basic.tsx
  src/examples/src/widgets/popup/MenuPopup.tsx
  src/examples/src/widgets/popup/SetWidth.tsx
  src/examples/src/widgets/popup/Underlay.tsx
  src/popup/README.md
  src/popup/index.tsx
  src/popup/popup.m.css
  src/popup/popup.m.css.d.ts
  src/popup/tests/Popup.spec.tsx
  src/theme/popup.m.css
  src/theme/popup.m.css.d.ts
Labels: dojo-7.0, new widget
