Repository dojo/widgets, pull requests merged in 2020-04, with the labels that each got.

#1280 v7 Migration guide for Helper-Text, Icon, and Label
  docs/V7-Migration-Guide.md
Labels: documentation, dojo-7.0

#1156 Pagination widget
  .dojorc
  src/examples/src/config.tsx
  src/examples/src/widgets/pagination/Basic.tsx
  src/examples/src/widgets/pagination/Controlled.tsx
  src/examples/src/widgets/pagination/PageSizeSelector.tsx
  src/examples/src/widgets/pagination/SiblingCount.tsx
  src/pagination/PageLink.tsx
  src/pagination/Pagination.nls.ts
  src/pagination/README.md
  src/pagination/index.tsx
  src/pagination/tests/Pagination.spec.tsx
  src/theme/default/pagination.m.css
  src/theme/default/pagination.m.css.d.ts
  src/theme/dojo/index.ts
  src/theme/dojo/pagination.m.css
  src/theme/dojo/pagination.m.css.d.ts
  src/theme/dojo/select.m.css
  src/theme/material/index.ts
  src/theme/material/pagination.m.css
  src/theme/material/pagination.m.css.d.ts
Labels: new widget

#1394 Fixed css type issues
  src/slide-pane/index.tsx
  src/slide-pane/styles/slide-pane.m.css.d.ts
  src/slide-pane/tests/unit/SlidePane.spec.tsx
  src/theme/default/slide-pane.m.css.d.ts
  src/theme/dojo/slide-pane.m.css.d.ts
  src/theme/material/slide-pane.m.css.d.ts
  src/theme/material/title-pane.m.css.d.ts
Labels: bug, dojo-7.0

#1384 V7 migration guide improvements
  docs/V7-Migration-Guide.md
Labels: dojo-7.0

#1438 IE11 Fixes
  src/theme/material/icon.m.css
  src/theme/material/text-input.m.css
Labels: bug, dojo-7.0

#1440 Checkbox/Radio/Switch required property changes
  src/checkbox-group/middleware.tsx
  src/checkbox-group/tests/CheckboxGroup.spec.tsx
  src/checkbox-group/tests/middleware.spec.tsx
  src/checkbox/index.tsx
  src/checkbox/tests/unit/Checkbox.spec.tsx
  src/examples/src/widgets/checkbox/Disabled.tsx
  src/examples/src/widgets/checkbox/Readonly.tsx
  src/examples/src/widgets/radio/Basic.tsx
  src/examples/src/widgets/radio/Disabled.tsx
  src/examples/src/widgets/radio/Labelled.tsx
  src/radio-group/middleware.ts
  src/radio-group/tests/RadioGroup.spec.tsx
  src/radio-group/tests/middleware.spec.ts
  src/radio/index.tsx
  src/radio/tests/unit/Radio.spec.tsx
  src/switch/index.tsx
  src/switch/tests/unit/Switch.spec.tsx
Labels: dojo-7.0

#1442 mobile improvements: Remove set widths from examples
  src/examples/src/widgets/avatar/Basic.tsx
  src/examples/src/widgets/avatar/Icon.tsx
  src/examples/src/widgets/avatar/Image.tsx
  src/examples/src/widgets/avatar/Secondary.tsx
  src/examples/src/widgets/avatar/Size.tsx
  src/examples/src/widgets/avatar/Variant.tsx
  src/examples/src/widgets/card/ActionButtons.tsx
  src/examples/src/widgets/card/ActionButtonsAndIcons.tsx
  src/examples/src/widgets/card/ActionIcons.tsx
  src/examples/src/widgets/card/Basic.tsx
  src/examples/src/widgets/card/CardCombined.tsx
  src/examples/src/widgets/card/CardWithMediaContent.tsx
  src/examples/src/widgets/card/CardWithMediaRectangle.tsx
  src/examples/src/widgets/header-card/ActionCard.tsx
  src/examples/src/widgets/header-card/Basic.tsx
  src/examples/src/widgets/header-card/MediaCard.tsx
Labels: dojo-7.0
